services:
    app:
        build: .
        container_name: be_app
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/BECK

    mongo:
        image: mongo:6
        container_name: be_mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: